language: node_js
node_js:
- '0.11'
before_script:
- npm install -g bower grunt-cli
- gem install sass
- bower install
services: mongodb
notifications:
  slack: moonshoot:BphAPBZjNZhbXyL2MVcVS8Ql
deploy:
  provider: heroku
  api_key:
    secure: c3KjMU9PG60qr0T2xbFyBZLQ6D/w6IwBIYcmRcwaojVmGXFhN/0yekzkZUdk7eoTpqkNtzkcabgxEEtIFe/UTJB9JhUFB/YcYCet80SwcnlxkHK66KaVTodeQgwBNmoMuYx0cdxUq3qMG8r4U5t0ElSdRBecjrSMvJ7Z2DUCn13CHq9hG40XBwfdTpRlt4r8qQXhkyrX69Sxs48IF1KpA0MFCR7/AJQA9coxTAYI+mHNCaEexzNolJq6bI+WlSKsydY3WBYjJoF7KqHJ5rjKf6p+W20UpeRwr6l5RU/f/R1ZJqtmFXhmrMGXS/GStPr5+prqyqn9TZ/kLLAA1QAb7pT6iUiB1Jh1iogcjuJR9cxFBmmBpRsGbvDeB3SONAYxU71TcMd/8lXKwWzf2kXPgePlDOw7vzTcCyR3JneBmohwGOZy7Zvs5Vp4uCxwA85FsjGu0I5v9RBjX2PcRyu1hppS2Uic5wdENLnXwQ1/PBXf9znKt20KtoHS7ZRM056qJLbbehW/jbpDTrPs2ElOpEkvi2PGhw2U2X0v6qznvPoehBc6R9w6HLyuSrgsiRM3qNH2o8Zm6vSyeBsTRFFOtfVKHtXl3W+oHIAVELVSfXig9w16DTZmvcj+FYf3/tVsG1M1QvmpVrG+rrYo5XU9OF0ck5RPX2zL6bh9tKZIbdI=
  app: stack
  on:
    repo: falconmoonshoot/stack
