#!/bin/bash
yum install -y nodejs npm --enablerepo=epel
npm install -g express forever bower grunt-cli
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080
mkdir -p /opt/app
