#!/bin/bash
sudo yum install -y nodejs npm --enablerepo=epel
sudo npm install -g express forever bower grunt-cli
sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080
cd /opt/app
gem install sass
npm install
bower install
grunt build
